export const STEPS = {
  FIRST_MOVE: 'FIRST_MOVE',
  TRAIL_SPLIT: 'TRAIL_SPLIT',
  BACK_TRAIL_SPLIT: 'BACK_TRAIL_SPLIT',
  CHEESE_FACTORY: 'CHEESE_FACTORY',
  CUCKOO: 'CUCKOO',
  KOLYBA: 'KOLYBA',
  LUNCH: 'LUNCH',
  TOP_MOUNTAIN: 'TOP_MOUNTAIN',
  WEATHER: 'WEATHER',
  WILD_BOAR: 'WILD_BOAR',
  DARK: 'DARK'
}